### ISSUE TITLE
 Expected y_max for bbox()to be in the range [0.0, 1.0], got 1.00725

### ISSUE THREAD

**Issue by Gintka** [huytranvan2010/Mosaic_data_augmentation_YOLO#1]
always got a coordinate greater than 1. but carefully examined labels used , they all between [0,1]

**Comment by huytranvan2010** [comment]
@Gintka Please give me more detail info: labels after augmentation... so that I can reproduce it

**Comment by huytranvan2010** [comment]
> Please give me more detail info: labels after augmentation... so that I can reproduce it
